### ISSUE TITLE
TypeError while pressing Ok button in widget dialog

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-widgets#18]
Hi.
I face the following error when I **press OK** in widget dialog.
It avoids closing dialog and the widget is not shown in desktop (although it seems the widget is created and is sending  corresponding http requests).
Could you help me where does the problem may come from?

![Screenshot from 2021-02-01 16-52-19](https://user-images.githubusercontent.com/70196035/106464435-e213cb80-64ad-11eb-818e-6b2eb3b53d97.png)

**Comment by andersevenrud** [comment]
Can you link the source code of your widget ? It looks like the error comes from there.

**Comment by mahsashadi** [comment]
Here is the link:
https://github.com/BurnaSmartLab/osjs-grafana-widget

But it works well in most cases.
I just face this problem in one of our systems, while the others works fine.

**Comment by andersevenrud** [comment]
> I just face this problem in one of our systems, while the others works fine.

Maybe an outdated `@osjs/client` dependency ? This is the only point of failure that I can see at this moment.

**Comment by mahsashadi** [comment]
No, npm update is done!

**Comment by andersevenrud** [comment]
Hm. I'm curious to know, why is the updating of the widget tied into the `init()` method ? This might cause some unintended side-effects because there is a chance you call `super.init()` multiple times there. This function is designed to run once and always after the widget constructor.

https://github.com/BurnaSmartLab/osjs-grafana-widget/blob/master/index.js#L552

But in any case...

> I just face this problem in one of our systems, while the others works fine.

And you are doing the exact same interactions when you try to reproduce this ? Can I reproduce this ?

**Comment by mahsashadi** [comment]
since we need to remove widget if the cancel button is clicked, we have to call init() before removing. 

no, unfortunately there is not an exact instruction for producing that.

**Comment by andersevenrud** [comment]
> since we need to remove widget if the cancel button is clicked, we have to call init() before removing.

This sounds a bit strange to me. Why can't the init method be used as normal ?

**Comment by mahsashadi** [comment]
> Maybe an outdated `@osjs/client` dependency ? This is the only point of failure that I can see at this moment.

This problem is solved.
As you said the `@osjs/client` was outdated!
Although we do `npm update`, due some reasons, the `@osjs/client`was updated with our own repository.

**Comment by miladhashemi** [comment]
> This sounds a bit strange to me. Why can't the init method be used as normal ?

Since our widget setting (chart type, measurement,...) needs to be set, first the widget dialog window is appeared (the widget with empty setting will be created).
We use boolean this.options.start to check wether we have a widget with empty setting (true), or a real widget is already created via clicking OK button (false).
Below lines of code check the situation where CANCEL button is clicked and we need to destroy the widget with empty setting

```js
const dialog = this.core
      .make('osjs/dialogs').create(options, callbackValue, callbackButton).render(callbackRender);
    dialog.win.on('destroy', ()=> {
      if (this.options.start) {  // This line checks dialog is opened for first time.
        // With this line we remove the widget from widget list.
        this.init(); 
        this.core.make('osjs/widgets').remove(this);
        this.core.make('osjs/widgets').save();
      }
    });
```

**Comment by andersevenrud** [comment]
> Since our widget setting (chart type, measurement,...) needs to be set, first the widget dialog window is appeared (the widget with empty setting will be created).

I would recommend looking into refactoring this a little bit. The methods that has to do with initialization is designed to run immediately after the constructor and deferring these calls may have some unwanted side-effects.

The `render()` function would be a better option as this is not tied to anything in your case. This could have the logic of showing the dialog gives an OK you can set a state, then call render again, which will detect the changed state and render the appropriate grafana.

> This problem is solved.

Glad to hear it :)
